$$resource-extension //= (firmware-entry,)

firmware = {
  firmware-name,                  ; inherited from RFC4108
  ? firmware-version,
  ? firmware-package-identifier,  ; inherited from RFC4108
  ? dependency,                   ; inherited from RFC4108
  ? component-index,              ; equivalent to RFC4108 fwPkgType
  ? block-device-identifier,
  ? target-hardware-identifier,   ; an RFC4108 alternative to model-label
  model-label,
  ? hash-entry,                   ; a hash for a single, incl. NI hash-algo index
  ? cms-firmware-package,         ; RCF4108, experimental, this is an actual firmware blob!
}

firmware-entry = (60: firmware / [ 2* firmware ])
firmware-name = (61 : text)
firmware-version = (62 : text / int)
component-index = (63 : int)
model-label = (64 text / int)
block-device-identifier = (65 : text / int)
cms-firmware-package = (66: bstr)
firmware-package-identifier = (67: text)
target-hardware-identifier = (68: text)
dependency = (69: { ? firmware-name,
                    ? firmware-version,
                    ? firmware-package-identifier,
                  }
             )
