$$payload-extension  //= (firmware-entry,)
$$evidence-extension  //= (firmware-entry,)

firmware-manifest = {
  firmware-manifest-id,
  firmware-manifest-creation-timestamp,
  firmware-manifest-version,
  firmware-manifest-description,
  firmware-manifest-nonce,
  ? firmware-manifest-aliases,
  ? firmware-manifest-dependencies,
  firmware-target-device-identifier,
  firmware-payload-entry,
  ? simple-firmware-manifest-extensions,
  $$firmware-manifest-extensions,
}

firmware-payload = {
  firmware-payload-id,
  ? firmware-package-identifier,
  firmware-payload-description,
  firmware-payload-format,
  firmware-payload-size,
  ? firmware-payload-simple-version,
  ? firmware-payload-version,
  firmware-payload-digests,
  ? firmware-target-component-index,
  firmware-target-storage-identifier,
  firmware-payload-conditions,
  ? firmware-payload-directives,
  ? firmware-target-dependency,
  ? firmware-target-minimal-version,
  ? firmware-payload-relationships,
  firmware-payload-package,
  ? simple-firmware-payload-extensions,
  $$firmware-payload-extensions,
}

firmware-entry = (59: firmware-manifest / [ 2* firmware-manifest ])
firmware-payload-entry = (60: firmware-payload / [ 2* firmware-payload ])
firmware-payload-id = (61: bytes / text / uint)
firmware-package-identifier = (62: text)
firmware-manifest-id = (63: bytes / text / int)
firmware-manifest-creation-timestamp = (64: time)
firmware-manifest-version = (65: uint)
firmware-manifest-description = (66: text)
firmware-manifest-nonce = (67: bytes)
firmware-manifest-dependencies = (68: resource-reference)
firmware-manifest-aliases = (69: resource-reference)
resource-reference = [ + [ resource-reference-uri: uri,
                           resource-reference-digest: bytes,
                         ],
                     ]
firmware-payload-description = (70: text)
firmware-payload-format = (71: { firmware-payload-format-type,
                                 ? firmware-payload-format-guidance,
                               }
                          )
firmware-payload-format-type = (72: int)
firmware-payload-format-guidance = (73: bytes)
firmware-payload-size = (74: uint)
firmware-payload-package = (75: { ? firmware-package-compression-type,
                                  ? firmware-package-compression-guidance,
                                  firmware-package,
                                }
                           )
firmware-package-compression-type = (76: text / int)
firmware-package-compression-guidance = (77: bytes)
firmware-package = (78: bytes)
firmware-target-component-index = (79: text)
firmware-target-storage-identifier = (80: bytes / text / int)
firmware-target-dependency = (81: [ ? { firmware-target-major-version,
                                        version-comparison,
                                        required-version,
                                      },
                                    ? { firmware-target-minor-version,
                                        version-comparison,
                                        required-version,
                                      },
                                    ? { firmware-target-revision-version,
                                        version-comparison,
                                        required-version,
                                      },
                                    ? { firmware-target-build-version,
                                        version-comparison,
                                        required-version,
                                      },
                                  ]
                             )
firmware-payload-relationships = (82: [ + { firmware-payload-relationship-type,
                                            firmware-payload-ids,
                                          },
                                      ]
                                )
firmware-payload-ids = (83: [ + ( bytes / text / int )])
firmware-payload-relationship-type = (84: $firmware-payload-relationship-types)
$firmware-payload-relationship-types /= patches-firmware
$firmware-payload-relationship-types /= requires-firmware
$firmware-payload-relationship-types /= supersedes-firmware
patches-firmware = 1
requires-firmware = 2
supersedes-firmware = 3
firmware-target-device-identifier = (85: { firmware-target-vendor-identifier,
                                           ? firmware-target-type-identifier,
                                           firmware-target-model-identifier,
                                           ? firmware-target-class-identifier,
                                           ? firmware-target-rfc4122-identifier,
                                           ? firmware-target-8021AR-identifier,
                                           $$firmware-target-identifier-extensions,
                                         }
                                    )
firmware-target-vendor-identifier = (86: text)
firmware-target-type-identifier = (87: text)
firmware-target-model-identifier = (88: text)
firmware-target-class-identifier = (89: text)
firmware-target-rfc4122-identifier = (90: text)
firmware-target-8021AR-identifier = (91: bytes)
firmware-target-minimal-version  = (92: { firmware-target-major-version,
                                          firmware-target-minor-version,
                                          ? firmware-target-revision-version,
                                          ? firmware-target-build-version,
                                          ? firmware-target-storage-identifier,
                                        },
                                   )
firmware-target-major-version = (93: uint)
firmware-target-minor-version = (94: uint)
firmware-target-revision-version = (95: uint)
firmware-target-build-version = (96: uint)
firmware-payload-digests = (97: [ + { firmware-digest-type,
                                      ? firmware-digest-config-guidance,
                                      firmware-digest,
                                    },
                                ]
                           )
firmware-digest-type = (98: $firmware-digest-types) 
$firmware-digest-types /= raw-payload-digest
$firmware-digest-types /= installed-payload-digest
$firmware-digest-types /= ciphertext-digest
$firmware-digest-types /= pre-image-digest
raw-payload-digest = 1
installed-payload-digest = 2
ciphertext-digest = 3
pre-image-digest = 4
firmware-digest-config-guidance = (99: bytes)
firmware-digest = (100: bytes)
firmware-payload-conditions = (101: [ + { firmware-payload-condition-type,
                                          firmware-payload-condition-parameters,
                                        },
                                    ]
                              )
firmware-payload-condition-parameters = (102: bytes)
firmware-payload-condition-type = (103: $firmware-payload-condition-types)
$firmware-payload-condition-types /= vendor-id-condition 
$firmware-payload-condition-types /= class-id-condition 
$firmware-payload-condition-types /= device-id-condition
$firmware-payload-condition-types /= best-before-condition
vendor-id-condition = 1
class-id-condition = 2
device-id-condition = 3
best-before-condition = 4
firmware-payload-directives = (104: [ + { firmware-payload-directive-type,
                                          firmware-payload-directive-parameters,
                                        },
                                    ]
                              )
firmware-payload-directive-parameters = (105: bytes)
firmware-payload-directive-type = (106: $firmware-payload-directive-types)
$firmware-payload-directive-types /= apply-immediately-directive
$firmware-payload-directive-types /= apply-after-directive
apply-immediately-directive = 1
apply-after-directive = 2
firmware-payload-simple-version = (107: uint)
firmware-payload-version = (108: { firmware-payload-major-version,
                                   firmware-payload-minor-version,
                                   ? firmware-payload-revision-version,
                                   ? firmware-payload-build-version,
                                 }
                           )
firmware-payload-major-version = (109: uint)
firmware-payload-minor-version = (110: uint)
firmware-payload-revision-version = (111: uint)
firmware-payload-build-version = (112: uint)
version-comparison = (113: eq / ne / lt / le / gt / ge)
required-version = (114: uint)
simple-firmware-manifest-extensions = (115: { + int => bytes })
simple-firmware-payload-extensions = (116: { + int => bytes })
eq = 0
ne = 1
lt = 2
le = 3
gt = 4
ge = 5
