signed-coswid /= #6.18(COSE-Sign-coswid)

protected-sign-coswid-header = {
    1 => int,                      ; algorithm identifier
    4 => bstr,                     ; key identifier
    * cose-label => cose-values,
}

unprotected-sign-coswid-header = {
    * cose-label => cose-values,
}

COSE-Sign-coswid = [
    protected: bstr .cbor protected-sign1-coswid-header,
    unprotected: unprotected-sign1-coswid-header,
    payload: bstr .cbor concise-swid-tag,
    signature: [ * COSE_Signature ],
]

COSE_Signature =  [
    protected: bstr .cbor protected-sign-coswid-header,
    unprotected: unprotected-sign-coswid-header,
    signature : bstr
]
